[package]
name = "elk-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5", features = ["desktop"] }
dioxus-desktop = "0.5"
dioxus-logger = "0.4"
btleplug = "0.11"
tokio = { version = "1.0", features = ["full"] }
uuid = "1.0"
chrono = "0.4"
num-bigint = "0.4"